language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm-nightly
      sudo: required
      dist: trusty
      group: edge
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/parallel-lint src test
  - ./vendor/bin/phpcs src --standard=psr2 -sp
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - mkdir -p build/logs
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - travis_retry php coveralls.phar -x coverage.clover
